title: testingchet
description: testingchettestingchettestingchettestingchettestingchet
template:
  repo: testingchet-template
  name: testingchet
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
